name: CI

on:
    pull_request:
        branches: ['*']
    push:
        branches: [main]
    merge_group:
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install deps (with cache)
              run: pnpm install

            - name: Check format
              run: pnpm format:check

            - name: Run eslint
              run: pnpm lint

            - name: Run typecheck
              run: pnpm typecheck

            - name: Run build
              run: pnpm build

            - name: Run tests
              run: pnpm test
